In [1]:
#importing required modules
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup
import seaborn as sns
import time

In [2]:
# Reading CSV file into dataframe
dataframe = pd.read_csv("CompanyList.csv")
dataframe

,Company Name,Industry,Rating,Highly rated,Critically_rated,Founded Year,Global Count,India Count
0,TCS,IT Services & Consulting,3.8,"Job Security, Work Life Balance","Promotions / Appraisal, Salary & Benefits, Wor...",1968 (56 yrs old),1 Lakh+,1 Lakh+
1,Accenture,IT Services & Consulting,4.0,"Company Culture, Skill Development / Learning,...",Promotions / Appraisal,1989 (35 yrs old),1 Lakh+,1 Lakh+
2,Cognizant,IT Services & Consulting,3.9,Skill Development / Learning,Promotions / Appraisal,1994 (30 yrs old),1 Lakh+,1 Lakh+
3,Wipro,IT Services & Consulting,3.8,Job Security,"Promotions / Appraisal, Salary & Benefits",1945 (79 yrs old),10k-50k,1 Lakh+
4,Capgemini,IT Services & Consulting,3.8,"Job Security, Work Life Balance, Skill Develop...","Promotions / Appraisal, Salary & Benefits",1967 (57 yrs old),1 Lakh+,1 Lakh+
...,...,...,...,...,...,...,...,...
495,Microland,IT Services & Consulting,3.5,"Promotions / Appraisal, Salary & Benefits, Wor...","Promotions / Appraisal, Salary & Benefits, Wor...",1989 (35 yrs old),1k-5k,1k-5k
496,MetLife,Insurance,4.3,"Work Life Balance, Job Security, Company Culture","Promotions / Appraisal, Salary & Benefits, Wor...",2008 (16 yrs old),10k-50k,1k-5k
497,SS&C TECHNOLOGIES,IT Services & Consulting,3.5,"Promotions / Appraisal, Work Life Balance, Wor...","Promotions / Appraisal, Work Life Balance, Wor...",NaN,NaN,NaN
498,Spark Minda,Auto Components,3.9,Promotions / Appraisal,Promotions / Appraisal,1958 (66 yrs old),1k-5k,1k-5k
499,Biological E,Biotechnology,4.2,"Job Security, Company Culture, Work Life Balance",Promotions / Appraisal,1953 (71 yrs old),1k-5k,1k-5k

In [3]:
"""drops complete row if Founded Year consists any invalid data like in few rows we have 10k-50k
which is invalid, by finding founded year with contains '-' """
dataframe.drop(dataframe[dataframe['Founded Year'].str.contains('-',na=False)].index)

,Company Name,Industry,Rating,Highly rated,Critically_rated,Founded Year,Global Count,India Count
0,TCS,IT Services & Consulting,3.8,"Job Security, Work Life Balance","Promotions / Appraisal, Salary & Benefits, Wor...",1968 (56 yrs old),1 Lakh+,1 Lakh+
1,Accenture,IT Services & Consulting,4.0,"Company Culture, Skill Development / Learning,...",Promotions / Appraisal,1989 (35 yrs old),1 Lakh+,1 Lakh+
2,Cognizant,IT Services & Consulting,3.9,Skill Development / Learning,Promotions / Appraisal,1994 (30 yrs old),1 Lakh+,1 Lakh+
3,Wipro,IT Services & Consulting,3.8,Job Security,"Promotions / Appraisal, Salary & Benefits",1945 (79 yrs old),10k-50k,1 Lakh+
4,Capgemini,IT Services & Consulting,3.8,"Job Security, Work Life Balance, Skill Develop...","Promotions / Appraisal, Salary & Benefits",1967 (57 yrs old),1 Lakh+,1 Lakh+
...,...,...,...,...,...,...,...,...
495,Microland,IT Services & Consulting,3.5,"Promotions / Appraisal, Salary & Benefits, Wor...","Promotions / Appraisal, Salary & Benefits, Wor...",1989 (35 yrs old),1k-5k,1k-5k
496,MetLife,Insurance,4.3,"Work Life Balance, Job Security, Company Culture","Promotions / Appraisal, Salary & Benefits, Wor...",2008 (16 yrs old),10k-50k,1k-5k
497,SS&C TECHNOLOGIES,IT Services & Consulting,3.5,"Promotions / Appraisal, Work Life Balance, Wor...","Promotions / Appraisal, Work Life Balance, Wor...",NaN,NaN,NaN
498,Spark Minda,Auto Components,3.9,Promotions / Appraisal,Promotions / Appraisal,1958 (66 yrs old),1k-5k,1k-5k
499,Biological E,Biotechnology,4.2,"Job Security, Company Culture, Work Life Balance",Promotions / Appraisal,1953 (71 yrs old),1k-5k,1k-5k

In [4]:
#drops the rows if elements from CVS file of founded year are invalid
invalid = dataframe[dataframe['Founded Year'].str.contains('-',na=False)].index
dataframe.drop(invalid,inplace=True)

In [5]:
#fills the missing values in founded year column by forward filling method
dataframe['Founded Year'] = dataframe['Founded Year'].fillna(method='pad')

# seperate columns are created with names Years old and founded year
dataframe['Years old']=dataframe['Founded Year'].apply(lambda x:" ".join(re.findall('\s\((.*?)\s[yrs]',str(x))))
#dataframe['Years old']=dataframe['Founded Year'].apply(lambda x:int(x[x.find('(')+1:x.find('yrs')].strip()) if type(x)==type('x') else np.NaN)
dataframe['Founded Year']=dataframe['Founded Year'].apply(lambda x:" ".join(re.findall('(\d{4})',str(x))))

C:\Users\vdnvs\AppData\Local\Temp\ipykernel_4064\3478908654.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataframe['Founded Year'] = dataframe['Founded Year'].fillna(method='pad')

In [6]:
#fills the missing values in Highly rated column by forward filling method
dataframe['Highly rated'] = dataframe['Highly rated'].fillna(method='pad')

C:\Users\vdnvs\AppData\Local\Temp\ipykernel_4064\3273257878.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataframe['Highly rated'] = dataframe['Highly rated'].fillna(method='pad')

In [7]:
dataframe

,Company Name,Industry,Rating,Highly rated,Critically_rated,Founded Year,Global Count,India Count,Years old
0,TCS,IT Services & Consulting,3.8,"Job Security, Work Life Balance","Promotions / Appraisal, Salary & Benefits, Wor...",1968,1 Lakh+,1 Lakh+,56
1,Accenture,IT Services & Consulting,4.0,"Company Culture, Skill Development / Learning,...",Promotions / Appraisal,1989,1 Lakh+,1 Lakh+,35
2,Cognizant,IT Services & Consulting,3.9,Skill Development / Learning,Promotions / Appraisal,1994,1 Lakh+,1 Lakh+,30
3,Wipro,IT Services & Consulting,3.8,Job Security,"Promotions / Appraisal, Salary & Benefits",1945,10k-50k,1 Lakh+,79
4,Capgemini,IT Services & Consulting,3.8,"Job Security, Work Life Balance, Skill Develop...","Promotions / Appraisal, Salary & Benefits",1967,1 Lakh+,1 Lakh+,57
...,...,...,...,...,...,...,...,...,...
495,Microland,IT Services & Consulting,3.5,"Promotions / Appraisal, Salary & Benefits, Wor...","Promotions / Appraisal, Salary & Benefits, Wor...",1989,1k-5k,1k-5k,35
496,MetLife,Insurance,4.3,"Work Life Balance, Job Security, Company Culture","Promotions / Appraisal, Salary & Benefits, Wor...",2008,10k-50k,1k-5k,16
497,SS&C TECHNOLOGIES,IT Services & Consulting,3.5,"Promotions / Appraisal, Work Life Balance, Wor...","Promotions / Appraisal, Work Life Balance, Wor...",2008,NaN,NaN,16
498,Spark Minda,Auto Components,3.9,Promotions / Appraisal,Promotions / Appraisal,1958,1k-5k,1k-5k,66
499,Biological E,Biotechnology,4.2,"Job Security, Company Culture, Work Life Balance",Promotions / Appraisal,1953,1k-5k,1k-5k,71

In [8]:
# converts lakhs into 100000 and k into 1000
def Count(con:pd.core.frame.DataFrame):
    for i in con:  
        try:
            c = (str(i).lower().replace(' lakh+','00000').replace(' lakh','00000').replace('k','000').split('-'))
            return int(max(c))
        except Exception as e:
            return np.NaN
dataframe['Global Count']=Count(dataframe['Global Count'])
dataframe['India Count'] = Count(dataframe['India Count'])

# fills missing value with mean

dataframe['Global Count'] = dataframe['Global Count'].fillna(dataframe['Global Count'].mean())
dataframe['India Count'] = dataframe['India Count'].fillna(dataframe['India Count'].mean())

In [9]:
## converting string literals to int
dataframe['Rating'].astype(float)
dataframe['Founded Year'].astype(int)
dataframe['Years old'].astype(float)

0      56.0
1      35.0
2      30.0
3      79.0
4      57.0
       ...
495    35.0
496    16.0
497    16.0
498    66.0
499    71.0
Name: Years old, Length: 495, dtype: float64

In [26]:
dataframe.describe()

           Rating  Global Count  India Count
count  495.000000         495.0        495.0
mean     3.950303      100000.0     100000.0
std      0.270018           0.0          0.0
min      3.000000      100000.0     100000.0
25%      3.800000      100000.0     100000.0
50%      4.000000      100000.0     100000.0
75%      4.100000      100000.0     100000.0
max      4.900000      100000.0     100000.0

In [25]:
dataframe.to_csv("CompanyList_cl.csv",index=False)